#%RAML 1.0 NamedExample
  -
    ID?: 0
    Name: Jane Doe
    Age: 50
    BloodGroup: AB
    ContactNumber: +1-787878232
    Email: jane@abc.com
  -
    ID?: 1
    Name: John Doe
    Age: 55
    BloodGroup: B+
    ContactNumber: +1-787878987
    Email: john@abc.com